# Generated by Django 4.2 on 2023-04-15 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CollectAll', '0003_alter_collection_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='CollectAll.collection'),
        ),
    ]
